### ISSUE TITLE
chore: Couldn't find audio file to add: Os

### ISSUE THREAD

**Issue by NsdHSO** [CleanCut/invaders#10]
I ran `cargo build && cargo build --release` and after I did `cargo run` and I received this error 

{ code: 2, kind: NotFound, message: "No such file or directory" }', /Users/{userName}/cargo/registry/src/github.com-1ecc6299db9ec823/rusty_audio-1.2.1/src/lib.rs:79:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

My cargo.toml is like this 
`
[dependencies]
crossterm = "0.20.0"
rusty_audio = "1.2"
rusty_time = "0.11"
`

**Comment by CleanCut** [comment]
It's not finding the audio file. Double-check your `.add("label", "some/audio_file.wav")` and the actual location/name of your audio file.

If you need help figuring it out, share your code and your directory listing here!

**Comment by NsdHSO** [comment]
Yes, indeed, then I close this issue
