### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by a-priestley** [CleanCut/invaders#11]
I tried running this using emojis instead of ascii characters, but it's causing rendering issues. In Windows terminal, when an emoji is removed from a coordinate, it leaves behind a smaller version of that emoji. In VS Code integrated terminal, it just doesn't show up in it's new spot after being moved.
The weird part is that in both of these issues only happen when the symbols are moved up, down, or left. Moving right renders correctly.

**Comment by CleanCut** [comment]
🤷🏻‍♂️ Bugs with emoji rendering of windows terminals is beyond the scope of this project. 

The crossterm project may be interest in hearing about this bug! I encourage you to [report it there](https://github.com/crossterm-rs/crossterm/issues).
